name: Build Container Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-container-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Login to RedHat Container Registry'
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{secrets.RH_USERNAME}}
          password: ${{secrets.RH_PASSWORD}}

      - name: 'Build Image'
        env: 
          KC_STORE_PASS: ${{secrets.KC_STORE_PASS}}
          KC_KEY_PASS: ${{secrets.KC_KEY_PASS}}
        run: |
          docker build -t ghcr.io/ckupe/rhbk-fips:latest -f Containerfile --build-arg KC_STORE_PASS=$KC_STORE_PASS .
          docker push ghcr.io/ckupe/rhbk-fips:latest
